GET http://localhost:5000/players

###

GET http://localhost:5000/players/636987983aa988c6cc9c54cc

###

POST http://localhost:5000/players
Content-Type: application/json

{
  "name": "Eric"
}

###

DELETE http://localhost:5000/players/63698e8b4774a7ec96482e61

### 
PATCH http://localhost:5000/players/636ac090833a6f12c6ee9df0
Content-Type: application/json

{
  "name": "Viktor"
}