GET http://localhost:8020/rounds

###

GET http://localhost:8020/rounds/roundSummary/631eb0f5-be3d-41df-93fe-011490eecfaf

###

GET http://localhost:8020/rounds/631eb0f5-be3d-41df-93fe-011490eecfaf

###

DELETE http://localhost:8020/rounds/19df6d95-d29d-4878-b70e-5c43b4db1ef0/Dudeson

### 
