GET http://localhost:8020/rounds

###

GET http://localhost:8020/rounds/roundSummary/08c159e5-af04-4cf8-bc26-fa9b1dd96027

###

GET http://localhost:8020/rounds/08c159e5-af04-4cf8-bc26-fa9b1dd96027

###

DELETE http://localhost:8020/rounds/2770abbb-2b60-4488-a208-58bad2f29d90/Mannen

### 

POST http://localhost:8020/rounds/roundEarnings/be994bec-449d-4b78-9f0a-53b3e9d980d5
Content-Type: application/json

{
"earnings": 
  [
    {
      "name":"Mannen",
      "earning":100
    }
  ]
}

###

POST http://localhost:8020/players/earnings
Content-Type: application/json

{
"name":"Martin"
}

###

POST http://localhost:8020/players/rounds
Content-Type: application/json

{
"name":"Dudeson"
}

###

GET http://localhost:8020/rounds/dealWinProbabilities/08c159e5-af04-4cf8-bc26-fa9b1dd96027/1
